services:
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    platform: linux/amd64
    container_name: chrome
    privileged: false
    restart: unless-stopped
    command:
      - "--no-sandbox"
      - "--disable-gpu"
      - "--disable-dev-shm-usage"
      - "--remote-debugging-address=0.0.0.0"
      - "--remote-debugging-port=9222"
      - "--hide-scrollbars"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    environment:
      HOME: /cache/chrome
      TZ: Europe/London
    healthcheck:
      interval: 30s
      retries: 5
      start_interval: 2s
      start_period: 15s
      test:
        - CMD
        - nc
        - "-z"
        - "-w"
        - "1"
        - 127.0.0.1
        - "9222"
      timeout: 5s
    volumes:
      - read_only: False
        source: chrome-cache
        target: /cache/chrome
        type: volume
        volume:
          nocopy: False
  meilisearch:
    image: getmeili/meilisearch
    platform: linux/amd64
    container_name: meilisearch
    privileged: False
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    environment:
      MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE: "true"
      MEILI_HTTP_ADDR: 0.0.0.0:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: "true"
      TZ: Europe/London
    healthcheck:
      interval: 30s
      retries: 5
      start_interval: 2s
      start_period: 15s
      test:
        - CMD
        - curl
        - "--request"
        - GET
        - "--silent"
        - "--output"
        - /dev/null
        - "--show-error"
        - "--fail"
        - http://127.0
    volumes:
      - bind:
          create_host_path: True
        read_only: False
        source: /home/simon/docker/karakeep/search
        target: /meili_data
        type: bind
  karakeep:
    image: gcr.io/karakeep-app/karakeep
    platform: linux/amd64
    container_name: karakeep
    privileged: False
    restart: unless-stopped
    depends_on:
      chrome:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4096M
    environment:
      API_URL: http://localhost:30147
      ASSETS_DIR: /data/
      BROWSER_WEB_URL: http://chrome:9222
      CRAWLER_FULL_PAGE_ARCHIVE: "true"
      CRAWLER_FULL_PAGE_SCREENSHOT: "true"
      CRAWLER_VIDEO_DOWNLOAD: "true"
      DATA_DIR: /data
      EMBEDDING_TEXT_MODEL: qwen3-embedding:8b
      INFERENCE_IMAGE_MODEL: llava:7b
      INFERENCE_TEXT_MODEL: gemma3:4b
      MEILI_ADDR: http://meilisearch:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL_INTERNAL: http://localhost:30147
      OLLAMA_BASE_URL: http://192.168.4.193:11434
      PORT: "30147"
      TZ: Europe/London
    healthcheck:
      interval: 30s
      retries: 5
      start_interval: 2s
      start_period: 15s
      test:
        - CMD
        - wget
        - "--quiet"
        - "--spider"
        - http://127.0.0.1:30147/api/health
      timeout: 5s
    ports:
      - host_ip: 0.0.0.0
        mode: ingress
        protocol: tcp
        published: 30147
        target: 30147
    volumes:
      - bind:
          create_host_path: True
        read_only: False
        source: /home/simon/docker/karakeep/data
        target: /data
        type: bind
volumes:
  chrome-cache: {}
