services:
  comfyui:
    image: mmartial/comfyui-nvidia-docker:ubuntu24_cuda12.6-latest
    container_name: comfyui
    ports:
      - 8188:8188
    volumes:
      - /mnt/docker/comfyui/run:/comfy/mnt
      - /mnt/docker/comfyui/basedir:/basedir
    environment:
      - PREINSTALL_TORCH=true
      - PREINSTALL_TORCH_CMD=pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126
      - USE_PIPUPGRADE=false
#      - USE_UV=true
      - WANTED_UID=1000
      - WANTED_GUD=1000
      - BASE_DIRECTORY=/basedir
      - SECURITY_LEVEL=normal
      - USE_NEW_MANAGER=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: 
                - gpu
                - compute
                - utility